Repository KUIT-BARO/BARO-FRONTEND, pull requests merged in 2025-06, with the labels that each got.

#15 [Fix/#14] packagemanager 삭제
  .github/workflows/autoSync.yml
  package.json
  pnpm-lock.yaml
Labels: 🦊 동희, 🔨 Fix

#16 [Init/#12] 프로젝트 폴더 구조 세팅
  src/api/.gitkeep
  src/assets/img/.gitkeep
  src/assets/svg/.gitkeep
  src/pages/home/components/.gitkeep
  src/pages/home/constant/.gitkeep
  src/pages/home/hooks/.gitkeep
  src/pages/home/types/.gitkeep
  src/pages/home/utils/.gitkeep
  src/routes/.gitkeep
  src/shared/components/.gitkeep
  src/shared/constant/.gitkeep
  src/shared/hooks/.gitkeep
  src/shared/types/.gitkeep
  src/shared/utils/.gitkeep
  src/styles/.gitkeep
Labels: 🐱 정현, 🎉 Init

#18 [init/#2] global styles
  index.html
  src/shared/styles/.gitkeep
  src/shared/styles/global.css.ts
  src/shared/styles/reset.css.ts
Labels: 🦊 동희, 🎉 Init

#24 [init#20] Router 세팅
  package.json
  pnpm-lock.yaml
  src/pages/home/Home.tsx
  src/pages/logIn/LogIn.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/promiseManage/PromiseManage.tsx
  src/pages/promiseProposal/PromiseProposal.tsx
  src/pages/promiseSelect/PromiseSelect.tsx
  src/pages/promiseStatus/PromiseStatus.tsx
  src/pages/promiseVote/PromiseVote.tsx
  src/pages/search/Search.tsx
  src/routes/Router.tsx
  src/routes/constant/Routes.ts
  src/shared/components/notFound/NotFound.tsx
  tsconfig.app.json
Labels: 🐱 정현, 🎉 Init
