Repository KUIT-BARO/BARO-FRONTEND, pull requests merged in 2025-07, with the labels that each got.

#32 [Refactor/#31] refactor setting
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/pages/home/Home.tsx
  src/pages/logIn/LogIn.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/promiseManage/PromiseManage.tsx
  src/pages/promiseProposal/PromiseProposal.tsx
  src/pages/promiseStatus/PromiseStatus.tsx
  src/pages/promiseVote/PromiseVote.tsx
  src/pages/search/Search.tsx
  src/router/Layout.tsx
  src/router/Router.tsx
  src/router/constant/Routes.ts
  src/shared/components/container/container.tsx
  src/shared/components/footer/Footer.tsx
  src/shared/components/header/Header.styles.ts
  src/shared/components/header/Header.tsx
  src/shared/components/loading/Loading.tsx
  src/shared/styles/.gitkeep
  src/shared/styles/global.css.ts
  src/shared/styles/layer.css.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🦊 동희, 🌈 Refactor

#38 [Fix/#36] storybook 실행 오류 해결
  pnpm-lock.yaml
  src/shared/components/header/Header.stories.ts
  vite.config.ts
Labels: 🐱 정현, 🔨 Fix

#51 [Init/#28] code rabbit
  .coderabbit.yaml
Labels: 🦊 동희, 🎉 Init

#40 [Feature/#30] button component
  .storybook/preview.ts
  src/shared/components/button/Button.css.ts
  src/shared/components/button/Button.stories.ts
  src/shared/components/button/Button.tsx
  src/shared/components/button/constant/button.ts
  src/shared/components/text/Text.css.ts
  src/shared/components/text/Text.tsx
  src/shared/constant/.gitkeep
  src/shared/styles/theme.css.ts
Labels: 🐱 정현, ✨Feature

#45 [Feature/#43] kakao map
  .gitignore
  package.json
  pnpm-lock.yaml
  public/icon/ic_location_dot.svg
  src/shared/components/kakaoMap/KakaoMap.css.ts
  src/shared/components/kakaoMap/KakaoMap.stories.ts
  src/shared/components/kakaoMap/KakaoMap.tsx
  src/shared/components/kakaoMap/constant/mapSize.ts
  src/shared/components/kakaoMap/hooks/useGetLocation.ts
  src/shared/components/kakaoMap/hooks/useKakaoLoader.ts
  src/shared/components/kakaoMap/hooks/usePlaceSearch.ts
  src/shared/components/kakaoMap/mockup.ts
  src/shared/components/kakaoMap/types/latLng.ts
  tsconfig.json
Labels: 🦊 동희, ✨Feature

#48 [Feature/#47] category tag component
  src/shared/components/categoryTag/CategoryTag.css.ts
  src/shared/components/categoryTag/CategoryTag.stories.tsx
  src/shared/components/categoryTag/CategoryTag.tsx
  src/shared/components/text/Text.css.ts
  src/shared/components/text/Text.tsx
  src/shared/constant/button.ts
  src/shared/constant/category.ts
  src/shared/styles/theme.css.ts
Labels: 🐱 정현, ✨Feature

#56 [Feature/#50] place thumbnail & list component
  src/shared/components/placeList/PlaceList.css.ts
  src/shared/components/placeList/PlaceList.stories.tsx
  src/shared/components/placeList/PlaceList.tsx
  src/shared/components/placeList/mockup.ts
  src/shared/components/placeThumbnail/PlaceThumbnail.css.ts
  src/shared/components/placeThumbnail/PlaceThumbnail.stories.tsx
  src/shared/components/placeThumbnail/PlaceThumbnail.tsx
Labels: 🐱 정현, ✨Feature

#64 [Refactor/#63] 약속 상태 상수 생성, place review 리펙토링, footer build 해결
  .storybook/preview.ts
  src/shared/components/button/Button.stories.ts
  src/shared/components/categoryTag/CategoryTag.css.ts
  src/shared/components/container/container.css.ts
  src/shared/components/footer/Footer.tsx
  src/shared/components/placeList/PlaceList.css.ts
  src/shared/components/placeList/PlaceList.tsx
  src/shared/components/placeList/mockup.ts
  src/shared/components/placeReview/PlaceReview.css.ts
  src/shared/components/placeReview/PlaceReview.stories.tsx
  src/shared/components/placeReview/PlaceReview.tsx
  src/shared/components/placeReview/PlaceReviewList.stories.tsx
  src/shared/components/placeReview/mockup.ts
  src/shared/components/placeReview/types/placeReviewSize.ts
  src/shared/components/placeThumbnail/PlaceThumbnail.stories.tsx
  src/shared/components/placeThumbnail/PlaceThumbnail.tsx
  src/shared/components/text/Text.css.ts
  src/shared/components/text/Text.tsx
  src/shared/constant/button.ts
  src/shared/constant/promiseStatus.ts
  src/shared/styles/global.css.ts
  src/shared/styles/theme.css.ts
Labels: 🦊 동희, 🌈 Refactor
