Repository KUIT-BARO/BARO-FRONTEND, pull requests merged in 2025-08, with the labels that each got.

#69 [Style/#68] css 변경
  src/shared/components/container/Container.css.ts
  src/shared/components/container/Container.tsx
  src/shared/components/header/Header.css.ts
Labels: 🦊 동희, 🎨 Style

#58 [Feature/#57] promise tracker component
  src/assets/svg/ic_pin_check.svg
  src/shared/components/promiseTracker/AvatarGroup.tsx
  src/shared/components/promiseTracker/ProgressBar.tsx
  src/shared/components/promiseTracker/PromiseTracker.css.ts
  src/shared/components/promiseTracker/PromiseTracker.stories.tsx
  src/shared/components/promiseTracker/PromiseTracker.tsx
  src/shared/components/promiseTracker/types/user.ts
  src/shared/components/promiseTracker/utils/calculateProgress.ts
  src/shared/components/promiseTracker/utils/groupUsers.ts
  src/shared/constant/promise.ts
Labels: 🐱 정현, ✨Feature

#66 [Init/#65] swagger ts api, tanstackquery v5 setting
  api/Auth.ts
  api/ErrorTest.ts
  api/HealthCheck.ts
  api/Pin.ts
  api/Places.ts
  api/Promises.ts
  api/Schedules.ts
  api/Users.ts
  api/data-contracts.ts
  api/http-client.ts
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/shared/queries/promise.ts
Labels: 🦊 동희, 🎉 Init

#99 [HOTFIX/#98] calendar 수정
  src/shared/components/calendar/utils/CalendarUtils.ts
Labels: 🦁 규운, ⚠️ HOTFIX

#100 [Feature/#92] Pending page
  public/icon/ic_place.png
  public/icon/ic_time.png
  src/pages/promiseStatus/PromiseStatus.tsx
  src/pages/promiseStatus/components/Confirmed.tsx
  src/pages/promiseStatus/components/Pending.css.ts
  src/pages/promiseStatus/components/Pending.tsx
  src/pages/promiseStatus/components/Voting.tsx
  src/pages/promiseStatus/components/popUp/PlacePopUp.css.ts
  src/pages/promiseStatus/components/popUp/PlacePopUp.tsx
  src/pages/promiseStatus/components/popUp/TimePopUp.css.ts
  src/pages/promiseStatus/components/popUp/TimePopUp.tsx
  src/pages/promiseStatus/components/popUp/timePopUp.css.ts
  src/pages/promiseStatus/components/popUp/timePopUp.tsx
  src/pages/promiseStatus/hooks/usePlace.ts
  src/pages/promiseStatus/hooks/useTime.ts
  src/pages/promiseStatus/mockUp.ts
  src/shared/components/calendar/Calendar.css.ts
  src/shared/components/popupOverlay/PopupOverlay.css.ts
  src/shared/components/promiseContainer/PromiseContainer.tsx
  src/shared/components/promiseDetail/PromisesDetail.css.ts
  src/shared/components/promiseDetail/PromisesDetail.stories.tsx
  src/shared/components/promiseDetail/PromisesDetail.tsx
  src/shared/components/promiseDetail/utils/getStatusLines.tsx
  src/shared/components/promiseDetail/utils/getStatusSet.tsx
  src/shared/components/promiseTracker/AvatarGroup.tsx
  src/shared/components/promiseTracker/types/user.ts
  src/shared/components/timeTable/TimeTable.css.ts
  src/shared/components/timeTable/TimeTable.tsx
  src/shared/components/timeTable/part/Colum.tsx
  src/shared/components/timeTable/part/Slot.tsx
  src/shared/components/timeTable/part/SlotTitle.tsx
  src/shared/constant/Days.ts
  src/shared/constant/avatar.ts
  src/shared/types/promisePlace.ts
  src/shared/utils/formatDateWithDay.ts
  src/shared/utils/renderAvator.tsx
Labels: 🦊 동희, ✨Feature
